---
- name: Check that the claimed_vlans file exists
  stat:
    path: "{{ workspace }}/claimed_vlans"
  register: stat_claimed_vlans

- name: Slurp claimed vlans file
  slurp:
    src: "{{ workspace }}/claimed_vlans"
  register: claimed_vlans_file
  when: stat_claimed_vlans.stat.exists == True

- name: Set facts from the claimed vlans
  set_fact:
    claimed_vlan_range: "{{ claimed_vlans_file['content'] | b64decode }}"
  when: stat_claimed_vlans.stat.exists == True

- name: Set more facts from the claimed vlans
  set_fact:
    maxvlan: "{{ claimed_vlan_range.split(':')[1] }}"
    minvlan: "{{ claimed_vlan_range.split(':')[0] }}"
  when: stat_claimed_vlans.stat.exists == True
