- job:
    name: pctp-base
    parent: third-base
    pre-run: playbooks/install-backwards-deps.yaml
    branches: master
    vars:
      workspace: "/home/ubuntu"

- job:
    name: ucsm-testjob
    parent: pctp-base
    pre-run: playbooks/dsvm-tempest-smoke-ucsm-job-pre.yaml
    run: playbooks/dsvm-tempest-smoke-ucsm-job.yaml
    post-run:
      - playbooks/dsvm-tempest-smoke-ucsm-job-post.yaml
    vars:
      override_zuul_branch: queens
    branches: master
