includes:
  # TODO: Rename this file. These functions are what enables single use nodes
  # in nodepool.
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: >
      Newly uploaded patchsets enter this pipeline to receive an initial +/-1
      Verified vote from Jenkins.
    success-message: "Build succeeded (check pipeline)."
    failure-message: "Build failed (check pipeline).  To recheck use 'recheck'."
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
    merge-failure:
      smtp:
        to: rcresswe@cisco.com
        from: zuul@cisco-openstack-ci.com
        subject: Upstream change {change} has a merge failure

  - name: asr-check
    description: >
      Pipeline for ASR specific jobs because they are rate limited by the
      amount of equipment. Newly uploaded patchsets enter this pipeline to
      receive an initial +/-1 Verified vote from Jenkins.
    success-message: "Build succeeded (asr-check pipeline)."
    failure-message: "Build failed (asr-check pipeline).  To recheck use 'recheck'."
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
    merge-failure:
      smtp:
        to: rcresswe@cisco.com
        from: zuul@cisco-openstack-ci.com
        subject: Upstream change {change} has a merge failure

  - name: experimental
    description: >
      Patchsets will enter this pipeline when a cisco-experimental comment is
      left on them. This pipeline is for running experimental jobs and allows
      for devs to test their changes to job code without impacting the ordinary
      running of the CI.
    success-message: Build succeeded (experimental pipeline).
    failure-message: Build failed (experimental pipeline).
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*cisco-experimental
    success:
      gerrit: {}
    failure:
      gerrit: {}


jobs:
  - name: ^.*$
    parameter-function: set_node_options

  - name: ^.*-ubuntu-czm$
    tags:
      - "reusenode"

  - name: ^.*-dsvm-.*$
    skip-if:
      - all-files-match-any:
        - ^.*\.rst$
        - ^api-ref/.*$
        - ^doc/.*$
        - ^install-guide/.*$
        - ^ironic/locale/.*$
        - ^ironic/tests/.*$
        - ^networking-cisco/tests/.*$
        - ^releasenotes/.*$
        - ^tools/.*$
        - ^tox.ini$

  - name: ^.*-asr1k-.*$
    skip-if:
      - all-files-match-any:
        - ^.*/plugins/ml2/.*$
        - ^.*networking_cisco/apps/.*$
        - ^.*networking_cisco/services/.*$
        - ^.*networking_cisco/tests/.*$

  - name: ^.*-ironic-cimc-nexus-.*$
    skip-if:
      - all-files-match-any:
        - ^.*/plugins/cisco.*$
        - ^.*networking_cisco/apps/.*$
        - ^.*networking_cisco/tests/.*$

projects:
  - name: openstack/networking-cisco
    check:
      - networking-cisco-dsvm-tempest-smoke-nexus-queens-centos-7-2-node
      - networking-cisco-dsvm-tempest-smoke-nexus-pike-centos-7-2-node
      - networking-cisco-dsvm-tempest-smoke-nexus-ocata-centos-7-2-node
      - networking-cisco-dsvm-tempest-smoke-nexus-newton-centos-7-2-node
      - networking-cisco-dsvm-tempest-smoke-nexus-mitaka-centos-7-2-node
      - networking-cisco-dsvm-tempest-smoke-ucsm-queens-centos-7
      - networking-cisco-dsvm-tempest-smoke-ucsm-pike-centos-7
      - networking-cisco-dsvm-tempest-smoke-ucsm-ocata-centos-7
      - networking-cisco-dsvm-tempest-smoke-ucsm-newton-centos-7
      - networking-cisco-dsvm-tempest-smoke-ucsm-mitaka-centos-7
      - ironic-dsvm-tempest-ironic-cimc-nexus-queens-centos-7-cimc
      - ironic-dsvm-tempest-ironic-cimc-nexus-pike-centos-7-cimc
      - ironic-dsvm-tempest-ironic-cimc-nexus-ocata-centos-7-cimc
    asr-check:
      - networking-cisco-dsvm-tempest-smoke-asr1k-queens-centos-7-asr
      - networking-cisco-dsvm-tempest-smoke-asr1k-pike-centos-7-asr
      - networking-cisco-dsvm-tempest-smoke-asr1k-ocata-centos-7-asr
      - networking-cisco-dsvm-tempest-smoke-asr1k-newton-centos-7-asr
      - networking-cisco-dsvm-tempest-smoke-asr1k-mitaka-centos-7-asr
    experimental:
      - networking-cisco-dsvm-tempest-smoke-nexus-queens-centos-7-2-node:
        - networking-cisco-dsvm-tempest-smoke-nexus-pike-centos-7-2-node
        - networking-cisco-dsvm-tempest-smoke-nexus-ocata-centos-7-2-node
        - networking-cisco-dsvm-tempest-smoke-nexus-newton-centos-7-2-node
        - networking-cisco-dsvm-tempest-smoke-nexus-mitaka-centos-7-2-node
      - networking-cisco-dsvm-tempest-smoke-ucsm-queens-centos-7:
        - networking-cisco-dsvm-tempest-smoke-ucsm-pike-centos-7
        - networking-cisco-dsvm-tempest-smoke-ucsm-ocata-centos-7
        - networking-cisco-dsvm-tempest-smoke-ucsm-newton-centos-7
        - networking-cisco-dsvm-tempest-smoke-ucsm-mitaka-centos-7
      - networking-cisco-dsvm-tempest-smoke-asr1k-queens-centos-7-asr:
        - networking-cisco-dsvm-tempest-smoke-asr1k-pike-centos-7-asr
        - networking-cisco-dsvm-tempest-smoke-asr1k-ocata-centos-7-asr
        - networking-cisco-dsvm-tempest-smoke-asr1k-newton-centos-7-asr
        - networking-cisco-dsvm-tempest-smoke-asr1k-mitaka-centos-7-asr
      - ironic-dsvm-tempest-ironic-cimc-nexus-queens-centos-7-cimc:
        - ironic-dsvm-tempest-ironic-cimc-nexus-pike-centos-7-cimc
        - ironic-dsvm-tempest-ironic-cimc-nexus-ocata-centos-7-cimc

  - name: openstack/ironic
    check:
      - ironic-dsvm-tempest-ironic-cimc-current-centos-7-cimc
    experimental:
      - ironic-dsvm-tempest-ironic-cimc-current-centos-7-cimc

  - name: openstack/cinder
    check:
      - cinder-dsvm-tempest-cisco-zonemanager-current-ubuntu-czm
    experimental:
      - cinder-dsvm-tempest-cisco-zonemanager-current-ubuntu-czm
