includes:
    #TODO: Rename this file. These functions are what enables single use nodes in nodepool.
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: "Build failed.  To recheck use 'cisco: recheck'.  For 3rd party ci contact info: https://wiki.openstack.org/wiki/ThirdPartySystems"
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
    merge-failure:
      smtp:
        to: rcresswe@cisco.com
        from: zuul@cisco-openstack-ci.com
        subject: Upstream change {change} has a merge failure


  - name: silent
    description: Newly uploaded patchsets enter this pipeline to check jobs whose results are NOT to be posted (because e.g. they are not yet stable)
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck
    success:
      smtp:
        to: rcresswe@cisco.com
        from: zuul@cisco-openstack-ci.com
        subject: 'Silent check of {change.project} {change.number},{change.patchset} passed'
    failure:
      smtp:
        to: rcresswe@cisco.com
        from: zuul@cisco-openstack-ci.com
        subject: 'Silent check of {change.project} {change.number},{change.patchset} failed'


jobs:
  - name: ^dsvm-tempest.*$
    parameter-function: single_use_node
  - name: noop-check-communication
    parameter-function: single_use_node

projects:
  - name: openstack-dev/ci-sandbox
    check:
      # Remove this after successfully verifying communication with upstream
      # and seeing a posted successful review.
      - noop-check-communication
    silent:
      # Uncomment this job when you have a jenkins slave running and want to
      # test a full Tempest run within devstack.
      - dsvm-tempest-full
