includes:
  # TODO: Rename this file. These functions are what enables single use nodes
  # in nodepool.
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: >
      Newly uploaded patchsets enter this pipeline to receive an initial +/-1
      Verified vote from Jenkins.
    failure-message: "Build failed.  To recheck use 'recheck'."
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
    merge-failure:
      smtp:
        to: rcresswe@cisco.com
        from: zuul@cisco-openstack-ci.com
        subject: Upstream change {change} has a merge failure


  - name: experimental
    description: >
      Patchsets will enter this pipeline when a cisco-experimental comment is
      left on them. This pipeline is for running experimental jobs and allows
      for devs to test their changes to job code without impacting the ordinary
      running of the CI.
    success-message: Build succeeded (experimental pipeline).
    failure-message: Build failed (experimental pipeline).
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*cisco-experimental
    success:
      gerrit: {}
    failure:
      gerrit: {}


jobs:
  - name: ^.*$
    parameter-function: set_node_options

  - name: ^.*-cinder-zonemanager-node$
    tags:
      - "reusenode"


projects:
  - name: openstack/networking-cisco
    check:
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-pike-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-ocata-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-newton-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-mitaka-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-pike-centos-7
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-ocata-centos-7
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-newton-centos-7
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-mitaka-centos-7
    experimental:
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-pike-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-ocata-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-newton-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-nexus-mitaka-centos-7-2-node
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-pike-centos-7
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-ocata-centos-7
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-newton-centos-7
      - gate-networking-cisco-dsvm-tempest-smoke-ucsm-mitaka-centos-7
      - gate-networking-cisco-dsvm-tempest-smoke-asr1k-pike-centos-7-asr
      - gate-networking-cisco-dsvm-tempest-smoke-asr1k-ocata-centos-7-asr
      - gate-networking-cisco-dsvm-tempest-smoke-asr1k-newton-centos-7-asr
      - gate-networking-cisco-dsvm-tempest-smoke-asr1k-mitaka-centos-7-asr

  - name: openstack/ironic
    check:
      - gate-ironic-dsvm-tempest-smoke-ironic-cimc-current-centos-7-cimc
    experimental:
      - gate-ironic-dsvm-tempest-smoke-ironic-cimc-current-centos-7-cimc

  - name: openstack/cinder
    experimental:
      - gate-cinder-dsvm-tempest-smoke-zm-cinder-current-cinder-zonemanager-node
