---
- name: Set the claimed VLANs on the Nexus interfaces for hosts
  include_role:
    name: static-nexus-programmer
  vars:
    nexus_interface: "{{ item }}"
    start_vlan: "{{ minvlan }}"
    end_vlan: "{{ maxvlan }}"
  with_items: "{{ nexus_interfaces }}"
