---
- name: Set the claimed VLANs on the Nexus interfaces for hosts
  include_role:
    name: static-nexus-programmer
  vars:
    nexus_interface: "{{ item }}"
    start_vlan: "{{ ansible_local.claimed_vlans.min_vlan }}"
    end_vlan: "{{ ansible_local.claimed_vlans.max_vlan }}"
  with_items: "{{ nexus_interfaces }}"
