---
- name: Fetch ubuntu image from the bridge VM
  fetch:
    src: "/home/tapuser/{{item}}"
    dest: "/tmp/images/{{item}}"
    flat: "yes"
  with_items:
    - ci-test-ubuntu-image-netboot.tar.gz
    - ci-test-ubuntu-image-localboot.tar.gz
    - ci-test-ubuntu-image-wholedisk.qcow2
  delegate_to: 10.0.0.24
  vars:
    ansible_private_key_file: /opt/nodepool-scripts/vm-bridge-key
    ansible_user: tapuser

- name: Ensure the image downloaded correctly
  copy:
    src: "/tmp/images/{{item}}"
    dest: "/tmp/images/{{item}}"
  with_items:
    - ci-test-ubuntu-image-netboot.tar.gz
    - ci-test-ubuntu-image-localboot.tar.gz
    - ci-test-ubuntu-image-wholedisk.qcow2
