---
- name: Fetch ubuntu image from the bridge VM
  fetch:
    src: "/home/tapuser/{{item}}"
    dest: "{{ zuul.executor.work_root }}/{{item}}"
    flat: "yes"
  with_items:
    - ci-test-ubuntu-image-netboot.tar.gz
    - ci-test-ubuntu-image-localboot.tar.gz
    - ci-test-ubuntu-image-wholedisk.qcow2
  delegate_to: 10.0.196.33
  vars:
    ansible_private_key_file: "{{ zuul.executor.work_root }}/vm-bridge-key"
    ansible_user: tapuser
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

- name: Create tmp dir for image to land in
  file:
    path: "/tmp/images"
    state: directory

- name: Ensure the image downloaded correctly
  copy:
    src: "{{ zuul.executor.work_root }}/{{item}}"
    dest: "/tmp/images/{{item}}"
  with_items:
    - ci-test-ubuntu-image-netboot.tar.gz
    - ci-test-ubuntu-image-localboot.tar.gz
    - ci-test-ubuntu-image-wholedisk.qcow2
