---
- name: Slurp nodepool node uuid
  slurp:
    src: /etc/nodepool/uuid
  register: nodepool_uuid_file

- name: Set tapid fact from node uuid
  set_fact:
    tapid: "{{ (nodepool_uuid_file['content'] | b64decode).split('-')[0] }}"

- name: Get nodepool node's private IP
  slurp:
    src: /etc/nodepool/node_private
  register: nodepool_private_ip_file

- name: Set private IP fact from file
  set_fact:
    private_nodepool_ip:
      "{{ nodepool_private_ip_file['content'] | b64decode | trim }}"

- name: Make sure GRE is allowed by iptables in rules file
  lineinfile:
    path: /etc/iptables/rules.v4
    line: '-A openstack-INPUT -p gre -j ACCEPT'
    insertafter: '-A openstack-INPUT -p icmp .*'
    state: present
  become: true

- name: Reload iptables rules from rules file
  command: "iptables-restore < /etc/iptables/rules.v4"
  become: true

# yamllint disable rule:line-length
- name: Setup l2 tunnels
  shell: |
    ip link add nexustap1 type gretap local {{ private_nodepool_ip | quote }} remote 10.0.0.24 key 1
    ip link add nexustap2 type gretap local {{ private_nodepool_ip | quote }} remote 10.0.0.24 key 2
    ip link set dev nexustap1 up
    ip link set dev nexustap2 up
  become: true
# yamllint enable

- name: Create OVS bridge to represent ex-net
  command: ovs-vsctl add-br br-ex
  become: true

- name: Create OVS bridge to represent phynet connected to nexus
  command: ovs-vsctl add-br br-nexusnet
  become: true

- name: Add l2 tunnel to nexus to the OVS bridge
  command: ovs-vsctl add-port br-nexusnet nexustap1
  become: true
  when: "'primary' in group_names"

- name: Add l2 tunnel to nexus to the OVS bridge
  command: ovs-vsctl add-port br-nexusnet nexustap2
  become: true
  when: "'subnodes' in group_names"

# yamllint disable rule:line-length
- name: Plumb the other side of the L2 tunnel
  raw: |
    sudo ip -o -d link | grep {{ private_nodepool_ip | quote }} | cut -d ' ' -f2 | cut -d '@' -f 1 | xargs -r -L 1 sudo ip link del && \
    sudo ip link add tap{{ tapid }}-1 type gretap local 10.0.0.24 remote {{ private_nodepool_ip | quote }} key 1 && \
    sudo ip link add tap{{ tapid }}-2 type gretap local 10.0.0.24 remote {{ private_nodepool_ip | quote }} key 2 && \
    sudo ip link set dev tap{{ tapid }}-1 up && \
    sudo ip link set dev tap{{ tapid }}-2 up && \
    sudo brctl addif nexusint1 tap{{ tapid }}-1 && \
    sudo brctl addif nexusint2 tap{{ tapid }}-2
  delegate_to: 10.0.0.24
  vars:
    ansible_private_key_file: /opt/nodepool-scripts/vm-bridge-key
    ansible_user: tapuser
# yamllint enable
