---
- name: Setup l2 tunnels
  shell: |
    ip link add nexustap1 type gretap local {{ private_nodepool_ip }} remote 10.0.0.24 key 1
    ip link add nexustap2 type gretap local {{ private_nodepool_ip }} remote 10.0.0.24 key 2
    ip link set dev nexustap1 up
    ip link set dev nexustap2 up
  become: true

- name: Create OVS bridge to represent ex-net
  command: ovs-vsctl add-br br-ex
  become: true

- name: Create OVS bridge to represent phynet connected to nexus
  command: ovs-vsctl add-br br-nexusnet
  become: true

- name: Add l2 tunnel to nexus to the OVS bridge
  command: ovs-vsctl add-port br-nexusnet nexustap1
  become: true
  when: "'primary' in group_names"

- name: Add l2 tunnel to nexus to the OVS bridge
  command: ovs-vsctl add-port br-nexusnet nexustap2
  become: true
  when: "'subnodes' in group_names"

- name: Plumb the other side of the L2 tunnel
  shell: |
    ip link add tap{{ tapid }}-1 type gretap local 10.0.0.24 remote {{ private_nodepool_ip }} key 1
    ip link add tap{{ tapid }}-2 type gretap local 10.0.0.24 remote {{ private_nodepool_ip }} key 2
    ip link set dev tap{{ tapid }}-1 up
    ip link set dev tap{{ tapid }}-2 up
  become: true
  become_user: tapuser
  become_method: sudo
  delegate_to: 10.0.0.24
  vars:
    ansible_private_key_file: /opt/nodepool-scripts/vm-bridge-key
    ansible_user: tapuser
