---
- name: Clear the claimed VLANs on the Nexus host interfaces
  include_role:
    name: static-nexus-programmer
  vars:
    nexus_interface: "{{ item }}"
    start_vlan: "{{ ansible_local.claimed_vlans.min_vlan }}"
    end_vlan: "{{ ansible_local.claimed_vlans.max_vlan }}"
    remove: "yes"
  with_items: "{{ nexus_interfaces }}"
  when: ansible_local.claimed_vlans is defined
