---
- name: install networking-cisco if not already present
  pip:
    name: networking-cisco
  become: true
  register: net_cisco_installed

- name: Copy script to workspace
  copy:
    src: "asr_clear_cfg.py"
    dest: "{{ workspace }}/asr_clear_cfg.py"

- name: Copy script device access config to workspace
  copy:
    src: "all.yaml"
    dest: "{{ workspace }}/all.yaml"

- name: ssh-keyscan the ASR1Ks
  command: "ssh-keyscan -t rsa {{ devices[item].ssh.ipaddr }}"
  register: asr_keyscan_result
  with_items: "{{ routers }}"

- name: Ensure ASR1Ks are in known_hosts
  known_hosts:
    name: "{{ devices[item.item].ssh.ipaddr }}"
    key: "{{ item.stdout }}"
  with_items: "{{ asr_keyscan_result.results }}"

- name: Execute command to program the ASR1K
  command: >
    python {{ workspace }}/asr_clear_cfg.py
    --config_file {{ workspace }}/all.yaml --regionID {{ region_id }}
  when: remove == "yes"
  ignore_errors: "yes"

- name: uninstall networking-cisco if it wasn't installed prior
  pip:
    name: networking-cisco
    state: absent
  become: true
  when: net_cisco_installed|changed
