---
- name: Copy script to workspace
  copy:
    src: "free_vlan.py"
    dest: "{{ workspace }}/free_vlan.py"

- name: Release the claimed VLANs
  command: >
    python {{ workspace }}/free_vlan.py
    {{ ansible_local.claimed_vlans.min_vlan }}
    {{ ansible_local.claimed_vlans.max_vlan }}
  register: command_output
  when: ansible_local.claimed_vlans is defined
