---
- name: Release the claimed region ID resource
  command: >
    python {{workspace}}/claim_ciresource.py release vlan
    /etc/ansible/facts.d/claimed_vlans.fact
  when: ansible_local.claimed_vlans is defined
