---
- hosts: all
  roles:
    - install-openvswitch
    - setup-l2-tunnels

- hosts: primary
  vars:
    nexus_interfaces: >
      {{ ci_node_interfaces }} +
      {{ routers|map('extract', connections, ['data', 'port'])|list }}
  roles:
    - claim-a-vlan-range
    - configure-vlan-for-hosts
    - role: setup-vlan-subinterface
      ip_cidr: 10.254.0.1/24
      subintf_vlan: "{{ ansible_local.claimed_vlans.min_vlan }}"
      subintf_mtu: "{{ physnet_mtu }}"
