---
- hosts: ci_log_servers
  tasks:
    - name: "Render out puppet environment"
      template:
        src: templates/puppet_manifests/log_server_common.yaml.j2
        dest: /etc/puppet/environments/common.yaml
      become: true

- hosts: ci_jenkins_servers
  tasks:
    - name: "Render out puppet environment"
      template:
        src: templates/puppet_manifests/ci_server_common.yaml.j2
        dest: /etc/puppet/environments/common.yaml
      become: true
