---
- hosts: all
  vars:
    additional_pip_libraries:
      - "ImcSdk==0.7.2"
      - "cryptography===2.1.4"
  roles:
    - install-openvswitch
    - setup-l2-tunnels
    - install-additional-pip-libraries

- hosts: primary
  vars:
    nexus_interfaces: "{{ ci_node_interfaces }}"
  roles:
    - claim-a-vlan-range
    - clear-nexus-vlans
    - claim-a-cimc-baremetal
    - configure-vlan-for-baremetal
    - configure-vlan-for-hosts
    - role: setup-vlan-subinterface
      ip_cidr: 10.1.0.2/26
      subintf_vlan: "{{ ansible_local.claimed_vlans.min_vlan }}"
      subintf_mtu: 1350
    - needs-ubuntu-images
  tasks:
    - name: Copy tftpd template into a known location
      copy:
        src: tftpd-xinetd.template
        dest: "/tmp/tftpd-xinetd.template"

    - name: Allow port 80 traffic on subinterface
      iptables:
        chain: INPUT
        action: insert
        destination: 10.1.0.2/32
        destination_port: 80
        protocol: tcp
        jump: ACCEPT
      become: true
