---
# Collect information from all nodes so we can use it in the devstack
# config file
- hosts: all
  tasks:
    - ping:

# Run devstack gate only on primary
- hosts: primary
  vars:
    projects:
      - openstack/networking-cisco
    nexus_interfaces: "{{ ci_node_interfaces }}"
    devstack_local_conf_src: templates/nexus_job_local_conf.j2
  roles:
    - load-devstack-localconf
    - run-devstack-gate
