---
# Run devstack gate only on primary
- hosts: primary
  vars:
    projects:
      - openstack/networking-cisco
    devstack_local_conf_src: templates/ucsm_job_local_conf.j2
  roles:
    - load-devstack-localconf
    - run-devstack-gate
