---
- hosts: primary
  vars:
    nexus_interfaces: >
      {{ ci_node_interfaces }} +
      {{ routers|map('extract', connections, ['data', 'port'])|list }}
  roles:
    - role: clear-nexus-vlans
      ignore_errors: true
    - role: clear-asr1k-cfg
      ignore_errors: true
    - release-claimed-vlans
    - release-claimed-region-id

- hosts: all
  roles:
    - tear-l2-tunnels
