---
# FIXME(sambetts) this should become part of the image build process
- hosts: all
  tasks:
    - file:
        path: /home/jenkins
        mode: 0755

- hosts: all
  vars:
    additional_pip_libraries:
      - "ImcSdk==0.7.2"
      - "cryptography===2.1.4"
  roles:
    - install-openvswitch
    - setup-l2-tunnels
    - install-additional-pip-libraries

- hosts: primary
  vars:
    nexus_interfaces: "{{ ci_node_interfaces }}"
  roles:
    - claim-a-vlan-range
    - clear-nexus-vlans
    - claim-a-cimc-baremetal
    - configure-vlan-for-baremetal
    - configure-vlan-for-hosts
    - role: setup-vlan-subinterface
      ip_cidr: 10.1.0.2/26
    - needs-ubuntu-images
  tasks:
    - name: Copy tftpd template into a known location
      copy:
        src: tftpd-xinetd.template
        dest: "/tmp/tftpd-xinetd.template"
