---
# Collect information from all nodes so we can use it in the devstack
# config file
- hosts: all
  tasks:
    - ping:

# Run devstack gate only on primary
- hosts: primary
  vars:
    projects:
      - openstack/ironic
      - openstack/python-ironicclient
      - openstack/ironic-python-agent
      - openstack/ironic-lib
    devstack_local_conf:
      "{{ lookup('template', 'templates/ironic_cimc_job_local_conf.j2') }}"
    devstack_gate_env_override:
      DEVSTACK_GATE_VIRT_DRIVER: "ironic"
      DEVSTACK_GATE_CONFIG_DRIVE: "1"
      DEVSTACK_GATE_TEMPEST_REGEX: "ironic"
  roles:
    - populate-ironic-hardware-info
    - run-devstack-gate
