---
- hosts: primary
  roles:
    # NOTE(sambetts) Ignore errors from clearing the nexus to make sure that
    # we release the vlans we claimed.
    - role: clear-nexus-vlans
      ignore_errors: true
    - release-claimed-vlans

- hosts: all
  roles:
    - tear-l2-tunnels
