---
- name: Copy script to workspace
  copy:
    src: "free_vlan.py"
    dest: "{{ workspace }}/free_vlan.py"

- name: Release the claimed VLANs
  command: "python {{ workspace }}/free_vlan.py {{ minvlan }} {{ maxvlan }}"
  register: command_output
  when: minvlan is defined and maxvlan is defined
